all:
  children:
    my_servers:
      hosts:
        redhat-bisooo:
          ansible_host: 44.235.148.242
          ansible_user: ec2-user
        ubuntu-bisooo:
          ansible_host: 34.216.95.4
    other_servers:
      hosts:
        redhat-other:
          ansible_host: 44.227.106.255
          ansible_user: ec2-user
        ubuntu-other:
          ansible_host: 54.70.40.40
