---
- name: Setup a web server
  hosts: ubuntu-bisooo
  become: true
  tasks:
    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: absent

    - name: Set the homepage html
      ansible.builtin.copy:
        src: page.html
        dest: /var/www/html/index.html

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
